# Generated by Django 4.2.4 on 2023-08-06 11:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='BookmarkModel',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeModel',
        ),
    ]
