# Generated by Django 4.2.4 on 2023-08-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_bookmark_bookmarkmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarkmodel',
            options={'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='likemodel',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
    ]
