# Generated by Django 4.2.4 on 2023-08-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profilemodel_id_alter_profilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='location',
        ),
    ]
