# Generated by Django 4.2.4 on 2023-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
