# Generated by Django 4.2.4 on 2023-08-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
