# Generated by Django 4.2.4 on 2023-08-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoModel',
        ),
    ]
